#!/usr/bin/ruby
# encoding: utf-8

$:.push("./lib")
require "jpegoptim"
require "em-pipe-run"

EM::run do
    puts Jpegoptim.available?.inspect
    Jpegoptim.optimize(["x.jpg"], { :preserve => true, :strip => :all, :debug => true }) do |results|
        puts results.inspect
    end
    
    puts "something"
end
